import 'package:flutter/material.dart';

/* Rectangle banner 1
    Autogenerated by FlutLab FTF Generator
  */
class BilltoLogo extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    double mHeight = MediaQuery.of(context).size.height;
    double mWidth = MediaQuery.of(context).size.width;
    print( mHeight);
    print(mWidth);
    double paddingTB = (mHeight*30)/100;
    return Container(
      //margin: const EdgeInsets.fromLTRB(32, 9, 32, 9),
      // padding: const EdgeInsets.all(22.5),
      padding: EdgeInsets.fromLTRB(0, (mHeight*3)/100, 0, (mHeight*3)/100),
      // decoration: BoxDecoration(
      //     border: Border.all(color: Colors.blueAccent)
      // ),

      child: ClipRRect(
        child: Image.asset(
          "assets/images/bill-to-logo.png",
          color: null,
          // height: 20,
          // width: 60,
          //fit: BoxFit.cover,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}