import 'package:flutter/material.dart';

/* Rectangle banner 1
    Autogenerated by FlutLab FTF Generator
  */
class BilltoLogo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 171.0,
      height: 76.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/bill-to-logo.png",
          color: null,
          fit: BoxFit.cover,
          width: 171.0,
          height: 76.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}